### ISSUE TITLE
Compile Error on OSX 10.8

### ISSUE THREAD

**Issue by jmel** [gregjurman/tesserwrap#11]
Hey Greg, 

When I try to compile tesserwrap on OSX10.8, I get the error below. /usr/local/lib contains the library files for tesseract libtesseract.a and libtesseract.dylib. I think that it is actually finding those files but then hitting trouble when trying to do the binding. Any suggestions would be greatly appreciated!

Thanks so much,
Jason

python setup.py install

-L/usr/local/lib
ld: library not found for -ltesseract_api
-L/usr/local/lib
ld: warning: -arch not specified
ld: symbol dyld_stub_binder not found (normally in libSystem.dylib).  Needed to perform lazy binding to function _main for inferred architecture x86_64
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    extra_lib_paths)
  File "setup.py", line 24, in find_closest_libname
    "Cannot find Tesseract via ldconfig, confirm it is installed.")
Exception: Cannot find Tesseract via ldconfig, confirm it is installed.

**Comment by jmel** [comment]
Looks like this fixes the OSX compile problem:

replace line 16 of setup.py with

return os.system('ld %s -arch x86_64 -execute -macosx_version_min 10.7 -pie -lm -lpthread -lcrt1.o -l%s' % (s_path, lib_name)) == 0

**Comment by gregjurman** [comment]
Ok, seeing as I finally have time this weekend to work on this, I'll look at getting this added.

**Comment by gregjurman** [comment]
jmel, see if the feature/osx branch works for you. I don't have a mac to test with.

**Comment by jmel** [comment]
That works for compile on osx.

**Comment by gregjurman** [comment]
Merged with master. Will release build to PyPI on Friday/Saturday.

**Comment by jmel** [comment]
Thanks Greg,

I'll try it out today.

Cheers,
Jason
