### ISSUE TITLE
Does not install

### ISSUE THREAD

**Issue by peoplecallmefrancois** [gregjurman/tesserwrap#14]
I get the following error, when I try to install tesserwrap using the `python setup.py install` command? How do I fix this?

`gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -O2 -DNDEBUG -g -O3 -I/usr/local/include -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c tesserwrap/cpp/tesseract_ext.cpp -o build/temp.macosx-10.6-intel-2.7/tesserwrap/cpp/tesseract_ext.o
gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -O2 -DNDEBUG -g -O3 -I/usr/local/include -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c tesserwrap/cpp/tesseract_wrap.cpp -o build/temp.macosx-10.6-intel-2.7/tesserwrap/cpp/tesseract_wrap.o
c++ -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-2.7/tesserwrap/cpp/tesseract_ext.o build/temp.macosx-10.6-intel-2.7/tesserwrap/cpp/tesseract_wrap.o -L/usr/local/lib -ltesseract-ocr -o build/lib.macosx-10.6-intel-2.7/libtesserwrap.so
ld: library not found for -ltesseract-ocr
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'c++' failed with exit status 1`

**Comment by gregjurman** [comment]
Can you give me an overview of your environment? Python version, Version of Tesseract, etc?

It looks like you are using clang on 10.6 which I have not tested with.

**Comment by peoplecallmefrancois** [comment]
I am on Mountain Lion, not sure why it says 10.6, Python version 2.7, Tesseract - the most recent version I presume, since I downloaded it from googlecode yesterday. Thanks for trying to help me out. I appreciate it. :)
