### ISSUE TITLE
Build error on ubuntu

### ISSUE THREAD

**Issue by caseman** [gregjurman/tesserwrap#4]
I get this building tesserwrap from pypi and git against tesseract 2.04, boost 1.46.1, and python 2.7.2

$ python setup.py install
running install
running bdist_egg
running egg_info
creating tesserwrap.egg-info
writing tesserwrap.egg-info/PKG-INFO
writing top-level names to tesserwrap.egg-info/top_level.txt
writing dependency_links to tesserwrap.egg-info/dependency_links.txt
writing manifest file 'tesserwrap.egg-info/SOURCES.txt'
reading manifest file 'tesserwrap.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: manifest_maker: MANIFEST.in, line 1: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

writing manifest file 'tesserwrap.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/tesserwrap
copying tesserwrap/tesseract.py -> build/lib.linux-x86_64-2.7/tesserwrap
copying tesserwrap/**init**.py -> build/lib.linux-x86_64-2.7/tesserwrap
running build_ext
building 'libtesserwrap' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/tesserwrap
creating build/temp.linux-x86_64-2.7/tesserwrap/cpp
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -I/usr/include/python2.7 -c tesserwrap/cpp/tesseract_wrap.cpp -o build/temp.linux-x86_64-2.7/tesserwrap/cpp/tesseract_wrap.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
In file included from tesserwrap/cpp/tesseract_wrap.cpp:1:0:
tesserwrap/cpp/tesseract_wrap.h:7:17: error: ‘tesseract’ is not a namespace-name
tesserwrap/cpp/tesseract_wrap.h:7:26: error: expected namespace-name before ‘;’ token
tesserwrap/cpp/tesseract_wrap.h: In member function ‘int TessBaseAPIExt::Get_Rect_Left()’:
tesserwrap/cpp/tesseract_wrap.h:20:42: error: ‘class TessBaseAPIExt’ has no member named ‘rect_left_’
tesserwrap/cpp/tesseract_wrap.h: In member function ‘int TessBaseAPIExt::Get_Rect_Top()’:
tesserwrap/cpp/tesseract_wrap.h:21:41: error: ‘class TessBaseAPIExt’ has no member named ‘rect_top_’
tesserwrap/cpp/tesseract_wrap.h: In member function ‘int TessBaseAPIExt::Get_Rect_Width()’:
tesserwrap/cpp/tesseract_wrap.h:22:43: error: ‘class TessBaseAPIExt’ has no member named ‘rect_width_’
tesserwrap/cpp/tesseract_wrap.h: In member function ‘int TessBaseAPIExt::Get_Rect_Height()’:
tesserwrap/cpp/tesseract_wrap.h:23:44: error: ‘class TessBaseAPIExt’ has no member named ‘rect_height_’
tesserwrap/cpp/tesseract_wrap.h: At global scope:
tesserwrap/cpp/tesseract_wrap.h:35:25: error: ‘PageSegMode’ has not been declared
tesserwrap/cpp/tesseract_wrap.h:36:5: error: ‘PageSegMode’ does not name a type
tesserwrap/cpp/tesseract_wrap.cpp: In constructor ‘Tesserwrap::Tesserwrap(const char_, const char_)’:
tesserwrap/cpp/tesseract_wrap.cpp:11:26: error: no matching function for call to ‘TessBaseAPIExt::Init(const char_&, const char_&)’
tesserwrap/cpp/tesseract_wrap.cpp:11:26: note: candidate is:
/usr/include/tesseract/baseapi.h:62:14: note: static int TessBaseAPI::Init(const char_, const char_, const char_, bool, int, char_*)
/usr/include/tesseract/baseapi.h:62:14: note:   candidate expects 6 arguments, 2 provided
tesserwrap/cpp/tesseract_wrap.cpp: At global scope:
tesserwrap/cpp/tesseract_wrap.cpp:29:1: error: ‘PageSegMode’ does not name a type
tesserwrap/cpp/tesseract_wrap.cpp:34:33: error: variable or field ‘SetPageSegMode’ declared void
tesserwrap/cpp/tesseract_wrap.cpp:34:33: error: ‘PageSegMode’ was not declared in this scope
tesserwrap/cpp/tesseract_wrap.cpp: In member function ‘void Tesserwrap::SetImage(std::string, int, int)’:
tesserwrap/cpp/tesseract_wrap.cpp:45:8: error: ‘class TessBaseAPIExt’ has no member named ‘SetImage’
tesserwrap/cpp/tesseract_wrap.cpp:46:8: error: ‘class TessBaseAPIExt’ has no member named ‘SetRectangle’
tesserwrap/cpp/tesseract_wrap.cpp: In member function ‘void Tesserwrap::Clear()’:
tesserwrap/cpp/tesseract_wrap.cpp:51:8: error: ‘class TessBaseAPIExt’ has no member named ‘Clear’
tesserwrap/cpp/tesseract_wrap.cpp: In member function ‘void Tesserwrap::SetRectangle(int, int, int, int)’:
tesserwrap/cpp/tesseract_wrap.cpp:55:8: error: ‘class TessBaseAPIExt’ has no member named ‘SetRectangle’
tesserwrap/cpp/tesseract_wrap.cpp: In member function ‘std::string Tesserwrap::GetUTF8Text()’:
tesserwrap/cpp/tesseract_wrap.cpp:60:22: error: ‘class TessBaseAPIExt’ has no member named ‘GetUTF8Text’
tesserwrap/cpp/tesseract_wrap.cpp: In function ‘void init_module_libtesserwrap()’:
tesserwrap/cpp/tesseract_wrap.cpp:72:11: error: ‘PageSegMode’ was not declared in this scope
tesserwrap/cpp/tesseract_wrap.cpp:72:22: error: template argument 1 is invalid
tesserwrap/cpp/tesseract_wrap.cpp:73:24: error: ‘PSM_AUTO’ was not declared in this scope
tesserwrap/cpp/tesseract_wrap.cpp:74:33: error: ‘PSM_SINGLE_COLUMN’ was not declared in this scope
tesserwrap/cpp/tesseract_wrap.cpp:75:32: error: ‘PSM_SINGLE_BLOCK’ was not declared in this scope
tesserwrap/cpp/tesseract_wrap.cpp:76:31: error: ‘PSM_SINGLE_LINE’ was not declared in this scope
tesserwrap/cpp/tesseract_wrap.cpp:77:31: error: ‘PSM_SINGLE_WORD’ was not declared in this scope
tesserwrap/cpp/tesseract_wrap.cpp:78:31: error: ‘PSM_SINGLE_CHAR’ was not declared in this scope
tesserwrap/cpp/tesseract_wrap.cpp:79:25: error: ‘PSM_COUNT’ was not declared in this scope
tesserwrap/cpp/tesseract_wrap.cpp:88:36: error: ‘GetPageSegMode’ is not a member of ‘Tesserwrap’
tesserwrap/cpp/tesseract_wrap.h: In member function ‘int TessBaseAPIExt::Get_Rect_Height()’:
tesserwrap/cpp/tesseract_wrap.h:23:57: warning: control reaches end of non-void function [-Wreturn-type]
tesserwrap/cpp/tesseract_wrap.h: In member function ‘int TessBaseAPIExt::Get_Rect_Width()’:
tesserwrap/cpp/tesseract_wrap.h:22:55: warning: control reaches end of non-void function [-Wreturn-type]
tesserwrap/cpp/tesseract_wrap.h: In member function ‘int TessBaseAPIExt::Get_Rect_Top()’:
tesserwrap/cpp/tesseract_wrap.h:21:51: warning: control reaches end of non-void function [-Wreturn-type]
tesserwrap/cpp/tesseract_wrap.h: In member function ‘int TessBaseAPIExt::Get_Rect_Left()’:
tesserwrap/cpp/tesseract_wrap.h:20:53: warning: control reaches end of non-void function [-Wreturn-type]
tesserwrap/cpp/tesseract_wrap.cpp: In member function ‘std::string Tesserwrap::GetUTF8Text()’:
tesserwrap/cpp/tesseract_wrap.cpp:61:1: warning: control reaches end of non-void function [-Wreturn-type]
error: command 'gcc' failed with exit status 1

Maybe some incompatibility in this toolchain?

**Comment by gregjurman** [comment]
Interesting let me spawn a Ubuntu VM to do some cross-testing. It's been building fine on Fedora 14-16 x86/64.
- Could you confirm that you have installed tesseract-dev and boost-dev? 
- What version of Ubuntu are you running?

I see another issue in that file that MANIFEST.in is borked. I just fixed it and uploaded a new sdist to PyPI and pushed here. Let me look into the gcc issue.

**Comment by gregjurman** [comment]
Issue replicated in VM. Looking for cause now.

**Comment by gregjurman** [comment]
Ubuntu is using Version 2.04 of Tesseract which does not use namespaces, need to add some preprocessor magic to fix that.

Work-around: For now remove Tesseract 2.04 and build/install 3.01.

**Comment by caseman** [comment]
Thanks, I got tesseract 3.01 installed, and with the most recent revision of tesseract I get this:

python setup.py install       ~/tesserwrap [master…]
running install
running bdist_egg
running egg_info
writing tesserwrap.egg-info/PKG-INFO
writing top-level names to tesserwrap.egg-info/top_level.txt
writing dependency_links to tesserwrap.egg-info/dependency_links.txt
reading manifest file 'tesserwrap.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'tesserwrap.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'libtesserwrap' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -I/usr/include/python2.7 -c tesserwrap/cpp/tesseract_wrap.cpp -o build/temp.linux-x86_64-2.7/tesserwrap/cpp/tesseract_wrap.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions build/temp.linux-x86_64-2.7/tesserwrap/cpp/tesseract_wrap.o -L/usr/local/lib -lboost_python -ltesseract_api -o build/lib.linux-x86_64-2.7/libtesserwrap.so
/usr/bin/ld: cannot find -ltesseract_api
collect2: ld returned 1 exit status
error: command 'g++' failed with exit status 1

I can get it to install by removing the reference to 'tesseract_api', but then it unsurprisingly won't import. I believe that I have all of the boost-dev packages installed (there are a lot), I definitely have the tesseract-dev package installed.

What version of boost were you testing with? Maybe there is a mismatch there,

Thanks.

**Comment by gregjurman** [comment]
Make sure libtesseract_api is in the library path.
1. Do an `updatedb` as root and `locate libtesseract_api`. 
2. Check that the `library_dirs` parameter in setup.py:14 has the directory path in the list.

I am working on a patch to fix the incompatibility with Tesseract 2.04. Tesseract 2.04 is missing things that 3.01 has so it will take a little bit to fix.

**Comment by tonyseek** [comment]
@caseman 
In some linux release such as archlinux, the library `libtesseract_api` may be renamed to `libtesseract`. Why not try to changed the name in `setup.py`?

**Comment by gregjurman** [comment]
Wow, for some reason I had completely forgotten about this ticket.

@tonyseek: Ubuntu last shipped with Tesseract 2.04, which does not have the same `libtesseract_api` and has an entirely different call structure. The issue is trying to detect the differences between the 3.0 and 2.0 without a `#define API_VERSION` or some other blatant #define that states the version number.

Thank you for pointing out about the Arch Linux difference as well. I will test there as well.

Rel-eng: This ticket will constitute a minor version change to v0.1.0 as it changes the underlying call-structure of the C extension.

**Comment by gregjurman** [comment]
it looks like Ubuntu caught up with Tesseract in 12.04. Fixes Arch linux as well.

Rel-eng: Version bumped to 0.0.13 rather than 0.1.0 because nothing changed in the extension.
